name: LorinthsCraftArrows
version: 1.1
description: Lorinths updated version of CraftArrows
main: me.lorinth.craftarrows.LorinthsCraftArrows
commands:
  lca:
    description: Access to LorinthsCraftArrows Commands
    permission: lca.admin