name: LorinthsCraftArrows
version: 1.3.3
description: Lorinths updated version of CraftArrows, adds 30 Custom Arrows
main: me.lorinth.craftarrows.LorinthsCraftArrows
softdepend: [Citizens, WorldGuard]
commands:
  lca:
    description: Access to LorinthsCraftArrows Commands